version: '3.8'

services:
  # Mesaj Kuyruğu (Haberleşme Köprüsü)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Mesaj iletim portu
      - "15672:15672" # Yönetim arayüzü (UI)
    networks:
      - ecommerce-net

  # Auth Servisi Veri Tabanı
  auth-db:
    image: mongo
    ports:
      - "27018:27017"  # Dışarıdan 27018, içeride 27017
    volumes:
      - auth-data:/data/db
    networks:
      - ecommerce-net

  # Auth Servisi
  auth-service:
    build: ./authservice
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://auth-db:27017/authdb
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET=gizli-anahtar-degistir
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - ecommerce-net

  # Product Servisi Veri Tabanı
  product-db:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - product-data:/data/db
    networks:
      - ecommerce-net

  # Product Servisi
  product-service:
    build: ./productservice
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://auth-db:27017/productdb # Using auth-db for now as shared or need to fix connection string if separate
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET=gizli-anahtar-degistir # Auth servisi ile ayni olmali
    depends_on:
      - product-db
      - rabbitmq
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge

volumes:
  auth-data:
  product-data: